name: Deploy Chatbot to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js (per eventuali dipendenze future)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Copia i file necessari nella directory docs
      - name: Prepare public directory
        run: |
          mkdir -p docs
          cp index.html docs/
          cp chatbot.js docs/
          touch docs/.nojekyll

      # Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
